package br.ufjf.iacity.main.gui;

import br.ufjf.iacity.algorithm.AbstractAlgorithmSearch;
import br.ufjf.iacity.algorithm.AbstractAlgorithmSearch.SearchMode;
import br.ufjf.iacity.algorithm.BacktrackingSearch;
import br.ufjf.iacity.algorithm.BreadthAndDepthSearch;
import br.ufjf.iacity.algorithm.OrderedSearch;
import br.ufjf.iacity.algorithm.events.ISearchStartedEventListener;
import br.ufjf.iacity.algorithm.events.ISearchStatusChangedEventListener;
import br.ufjf.iacity.algorithm.events.ISearchStoppedEventListener;
import br.ufjf.iacity.algorithm.transition.AlphabeticalTransition;
import br.ufjf.iacity.graph.CityGraph;
import br.ufjf.iacity.graph.CityNodeGraph;
import br.ufjf.iacity.helper.GeoCoordinate;
import br.ufjf.iacity.helper.algorithm.AlgorithmParameter;
import br.ufjf.iacity.helper.file.FileHelper;
import br.ufjf.iacity.model.City;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class IACityGUI extends JFrame implements 
        ISearchStartedEventListener,
        ISearchStoppedEventListener,
        ISearchStatusChangedEventListener
{
    private AlgorithmParameter searchParameter;
    private AbstractAlgorithmSearch algorithmSearch;
    private long startSearchTime;
    private long endSearchTime;
    
    /**
     * Creates new form IACityGUI
     */
    public IACityGUI() 
    {
        this.searchParameter = new AlgorithmParameter();
        
        initComponents();
        initEvents();
        configComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroupCreateGraph = new javax.swing.ButtonGroup();
        radioGroupSearchAlgorithm = new javax.swing.ButtonGroup();
        radioGroupSearchTransition = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        radioManualGraph = new javax.swing.JRadioButton();
        radioTxtFileGraph = new javax.swing.JRadioButton();
        radioMapsGraph = new javax.swing.JRadioButton();
        btnCreateGraph = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnShowGraph = new javax.swing.JButton();
        btnSaveGraph = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        radioBTSearch = new javax.swing.JRadioButton();
        radioBreadthSearch = new javax.swing.JRadioButton();
        radioDepthSearch = new javax.swing.JRadioButton();
        radioOrderedSearch = new javax.swing.JRadioButton();
        radioBestFirstSearch = new javax.swing.JRadioButton();
        radioASearch = new javax.swing.JRadioButton();
        radioIDASearch = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        checkBoxEnableDuplicated = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        radioAlphabeticalTransition = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtStartNodeID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEndNodeID = new javax.swing.JTextField();
        btnSetStartAndEndNode = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnStartSearch = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        labelStatusSearchInfo = new javax.swing.JLabel();
        labelAlgorithmSearchInfo = new javax.swing.JLabel();
        labelSearchExecutionTimeInfo = new javax.swing.JLabel();
        labelSearchCostInfo = new javax.swing.JLabel();
        labelSearchDepthInfo = new javax.swing.JLabel();
        labelExpandedNodeCountInfo = new javax.swing.JLabel();
        labelVisitedNodeCountInfo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSearchPathInfo = new javax.swing.JTextArea();
        labelAverageFactorBranching = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnShowSearchTree = new javax.swing.JButton();
        btnSaveResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IACity");
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Defina as configurações desejadas para a execução dos algoritmos de IA");

        jTabbedPane2.setFont(jTabbedPane2.getFont().deriveFont(jTabbedPane2.getFont().getSize()+1f));

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+3f));
        jLabel3.setText("Escolha a forma de obter os dados para construção do grafo de cidades");

        radioGroupCreateGraph.add(radioManualGraph);
        radioManualGraph.setFont(radioManualGraph.getFont().deriveFont(radioManualGraph.getFont().getSize()+1f));
        radioManualGraph.setText("Inserir manualmente os dados");

        radioGroupCreateGraph.add(radioTxtFileGraph);
        radioTxtFileGraph.setFont(radioTxtFileGraph.getFont().deriveFont(radioTxtFileGraph.getFont().getSize()+1f));
        radioTxtFileGraph.setText("Obter os dados de arquivo texto");

        radioGroupCreateGraph.add(radioMapsGraph);
        radioMapsGraph.setFont(radioMapsGraph.getFont().deriveFont(radioMapsGraph.getFont().getSize()+1f));
        radioMapsGraph.setText("Obter os dados usando o Google Maps");

        btnCreateGraph.setFont(btnCreateGraph.getFont().deriveFont(btnCreateGraph.getFont().getSize()+3f));
        btnCreateGraph.setText("Criar Grafo");
        btnCreateGraph.setPreferredSize(new java.awt.Dimension(73, 25));
        btnCreateGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateGraphActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnShowGraph.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnShowGraph.setText("Ver Grafo");
        btnShowGraph.setEnabled(false);
        btnShowGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowGraphActionPerformed(evt);
            }
        });

        btnSaveGraph.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSaveGraph.setText("Salvar Grafo");
        btnSaveGraph.setActionCommand("Salvar Grafo");
        btnSaveGraph.setEnabled(false);
        btnSaveGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveGraphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShowGraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveGraph)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioTxtFileGraph)
                            .addComponent(radioManualGraph)
                            .addComponent(jLabel3)
                            .addComponent(radioMapsGraph)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnCreateGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(radioManualGraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioTxtFileGraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioMapsGraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCreateGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );

        jTabbedPane2.addTab("Grafo de Cidades", jPanel1);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Escolha o algoritmo de busca que será utilizado");

        radioGroupSearchAlgorithm.add(radioBTSearch);
        radioBTSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioBTSearch.setText("Backtracking");

        radioGroupSearchAlgorithm.add(radioBreadthSearch);
        radioBreadthSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioBreadthSearch.setText("Breadth");

        radioGroupSearchAlgorithm.add(radioDepthSearch);
        radioDepthSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioDepthSearch.setText("Depth");

        radioGroupSearchAlgorithm.add(radioOrderedSearch);
        radioOrderedSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioOrderedSearch.setText("Ordered");

        radioGroupSearchAlgorithm.add(radioBestFirstSearch);
        radioBestFirstSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioBestFirstSearch.setText("BestFirst");

        radioGroupSearchAlgorithm.add(radioASearch);
        radioASearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioASearch.setText("A*");

        radioGroupSearchAlgorithm.add(radioIDASearch);
        radioIDASearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioIDASearch.setText("IDA*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioDepthSearch)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBTSearch)
                            .addComponent(radioBreadthSearch))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioASearch)
                            .addComponent(radioBestFirstSearch)
                            .addComponent(radioIDASearch)))
                    .addComponent(radioOrderedSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBTSearch)
                    .addComponent(radioBestFirstSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBreadthSearch)
                    .addComponent(radioASearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDepthSearch)
                    .addComponent(radioIDASearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioOrderedSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Marque as opções que serão usadas durante a busca");

        checkBoxEnableDuplicated.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkBoxEnableDuplicated.setText("Habilitar a possiblidade de adicionar estados duplicados na árvore de busca");
        checkBoxEnableDuplicated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxEnableDuplicatedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxEnableDuplicated)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(checkBoxEnableDuplicated)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Escolher a regra de transição que será aplicada durante a busca");

        radioGroupSearchTransition.add(radioAlphabeticalTransition);
        radioAlphabeticalTransition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioAlphabeticalTransition.setText("Ordem alfabética dos nomes das cidades");
        radioAlphabeticalTransition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlphabeticalTransitionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAlphabeticalTransition)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(radioAlphabeticalTransition)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Selecione o nó inicial e final do grafo de cidades");

        txtStartNodeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ID do nó inicial:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("ID do nó final:");

        txtEndNodeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnSetStartAndEndNode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSetStartAndEndNode.setText("Definir");
        btnSetStartAndEndNode.setEnabled(false);
        btnSetStartAndEndNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetStartAndEndNodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStartNodeID, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnSetStartAndEndNode))
                            .addComponent(txtEndNodeID, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartNodeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndNodeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSetStartAndEndNode)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Algoritmos de IA", jPanel2);

        btnStartSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnStartSearch.setText("Buscar");
        btnStartSearch.setEnabled(false);
        btnStartSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSearchActionPerformed(evt);
            }
        });

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        labelStatusSearchInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStatusSearchInfo.setText("Status:  Parado");

        labelAlgorithmSearchInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAlgorithmSearchInfo.setText("Algoritmo de IA: Nenhum selecionado");

        labelSearchExecutionTimeInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSearchExecutionTimeInfo.setText("Tempo de Execução: 0 ms");

        labelSearchCostInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSearchCostInfo.setText("Custo da Solução: 0");

        labelSearchDepthInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSearchDepthInfo.setText("Profundidade da Solução: 0");
        labelSearchDepthInfo.setToolTipText("");

        labelExpandedNodeCountInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelExpandedNodeCountInfo.setText("Quantidade de Nós Expandidos: 0");

        labelVisitedNodeCountInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelVisitedNodeCountInfo.setText("Quantidade de Nós Visitados: 0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Caminho:");

        txtSearchPathInfo.setEditable(false);
        txtSearchPathInfo.setColumns(20);
        txtSearchPathInfo.setLineWrap(true);
        txtSearchPathInfo.setRows(5);
        jScrollPane1.setViewportView(txtSearchPathInfo);

        labelAverageFactorBranching.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAverageFactorBranching.setText("Fator Médio de Ramificação: 0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelAverageFactorBranching, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(labelVisitedNodeCountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelExpandedNodeCountInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSearchDepthInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAlgorithmSearchInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(labelStatusSearchInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSearchExecutionTimeInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSearchCostInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlgorithmSearchInfo)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(labelStatusSearchInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelSearchExecutionTimeInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelSearchCostInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelSearchDepthInfo)
                        .addGap(14, 14, 14)
                        .addComponent(labelExpandedNodeCountInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelVisitedNodeCountInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAverageFactorBranching)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Status da Busca");

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnShowSearchTree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnShowSearchTree.setText("Ver Árvore");
        btnShowSearchTree.setEnabled(false);
        btnShowSearchTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSearchTreeActionPerformed(evt);
            }
        });

        btnSaveResult.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSaveResult.setText("Salvar Resultado");
        btnSaveResult.setEnabled(false);
        btnSaveResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowSearchTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShowSearchTree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(btnStartSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnStartSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        jTabbedPane2.addTab("Buscar", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // <editor-fold defaultstate="collapsed" desc="Initialize Events">
    private void initEvents()
    {
        radioBTSearch.addActionListener(this::radioGroupSearchAlgorithmActionPerformed);
        radioBreadthSearch.addActionListener(this::radioGroupSearchAlgorithmActionPerformed);
        radioDepthSearch.addActionListener(this::radioGroupSearchAlgorithmActionPerformed);
        radioOrderedSearch.addActionListener(this::radioGroupSearchAlgorithmActionPerformed);
        radioBestFirstSearch.addActionListener(this::radioGroupSearchAlgorithmActionPerformed);
        radioASearch.addActionListener(this::radioGroupSearchAlgorithmActionPerformed);
        radioIDASearch.addActionListener(this::radioGroupSearchAlgorithmActionPerformed);
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Configure Components">
    private void configComponents()
    {
        
    }
    // </editor-fold>
    
    private void btnCreateGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateGraphActionPerformed
        // Limpa nós inicial e final do grafo anterior
        searchParameter.setStartCityNode(null);
        searchParameter.setEndCityNode(null);
        
        this.txtStartNodeID.setText("");
        this.txtEndNodeID.setText("");
        
         // Limpa o status anterior
        this.clearStatus();
        
        // Elimina a busca anterior
        algorithmSearch = null;
        
        if(radioManualGraph.isSelected())
        {
            ManualCreateGraphGUI manualGraphGUI = new ManualCreateGraphGUI();
            manualGraphGUI.setModal(true);
            manualGraphGUI.setVisible(true);
            
            List<String> verticesList = manualGraphGUI.getListVertices();
            List<String> adjacencyList = manualGraphGUI.getListAdjacency();
            
            CityGraph graph = CityGraph.createGraphFromStringsList(verticesList, adjacencyList);
            searchParameter.setGraph(graph);
        }
        else if(radioTxtFileGraph.isSelected())
        {
            try 
            {
                CityGraph graph = null;
                
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogType(JFileChooser.OPEN_DIALOG);
                fileChooser.setCurrentDirectory(new File(FileHelper.WORK_DIR));

                if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) 
                {
                    graph = FileHelper.loadGraphFile(fileChooser.getSelectedFile().getName());
                }
                
                searchParameter.setGraph(graph);
            } 
            catch (Exception ex) 
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else
        {
//            CityGraph graph = createGraph();
            CityGraph graph = randomGraph(100, 1);
            searchParameter.setGraph(graph);
        }
        
        // Habilita botões
        this.btnShowGraph.setEnabled(true);
        this.btnSaveGraph.setEnabled(true);
        this.btnSetStartAndEndNode.setEnabled(true);
        this.btnStartSearch.setEnabled(true);
        
        this.btnShowSearchTree.setEnabled(false);
        
        if(searchParameter.getGraph() != null)
        {
            JOptionPane.showMessageDialog(this, "O grafo foi criado, selecione as opções do algoritmo.");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Não foi possível criar o grafo.");
        }
    }//GEN-LAST:event_btnCreateGraphActionPerformed

    private void btnStartSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSearchActionPerformed
        if (searchParameter.getSearchMode() == null)
        {
            JOptionPane.showMessageDialog(this, "Algoritmo de busca não selecionado");
        }
        else if (searchParameter.getGraph() == null) 
        {
            JOptionPane.showMessageDialog(this, "O grafo não foi criado");
        }
        else if (searchParameter.getTransition() == null) 
        {
            JOptionPane.showMessageDialog(this, "A regra de transição não foi definida");
        }
        else if (searchParameter.getStartCityNode() == null) 
        {
            JOptionPane.showMessageDialog(this, "O nó inicial não foi definido");
        }
        else if (searchParameter.getEndCityNode() == null)
        {
            JOptionPane.showMessageDialog(this, "O nó final não foi definido");
        }
        else
        {
            // Reseta o grafo para o estado inicial
            searchParameter.getGraph().resetState();

            switch (searchParameter.getSearchMode().toString().toUpperCase())
            {
                case "BACKTRACKING":
                    algorithmSearch = new BacktrackingSearch(searchParameter);
                    break;
                case "BREADTH":
                case "DEPTH":
                    algorithmSearch = new BreadthAndDepthSearch(searchParameter);
                    break;
                case "ORDERED":
                    algorithmSearch = new OrderedSearch(searchParameter);
                    break;
                case "BESTFIRST":
                    
                    break;
                case "A*":
                    
                    break;
                case "IDA":
                    
                    break;
            }
            
            if(algorithmSearch != null)
            {
                // Adicionando eventos para do algoritmo de busca
                algorithmSearch.addSearchStartedEventListener(this);
                algorithmSearch.addSearchStoppedEventListener(this);
                algorithmSearch.addSearchStatusChangedEventListener(this);
                
                algorithmSearch.search();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Não foi possível instanciar um algoritmo de busca");
            }
        }
    }//GEN-LAST:event_btnStartSearchActionPerformed

    private void checkBoxEnableDuplicatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxEnableDuplicatedActionPerformed
        searchParameter.setEnableDuplicated(!searchParameter.isEnableDuplicated());
    }//GEN-LAST:event_checkBoxEnableDuplicatedActionPerformed

    private void btnShowSearchTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSearchTreeActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run() 
            {
                TreeViewerGUI frame = new TreeViewerGUI(algorithmSearch.getSearchTree().getRootNode());
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnShowSearchTreeActionPerformed

    private void btnSetStartAndEndNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetStartAndEndNodeActionPerformed
        if (searchParameter.getGraph() == null) 
        {
            JOptionPane.showMessageDialog(this, "O grafo não foi criado");
        }
        else
        {
            CityGraph graph = searchParameter.getGraph();
            
            CityNodeGraph startNode = graph.getNode(txtStartNodeID.getText().replaceAll(" ", ""));
            
            if(startNode == null)
            {
                JOptionPane.showMessageDialog(this, "O nó inicial não foi encontrado no grafo");
            }
            else
            {
                searchParameter.setStartCityNode(startNode);
            }
            
            CityNodeGraph endNode = graph.getNode(txtEndNodeID.getText().replaceAll(" ", ""));
            
            if(endNode == null)
            {
                JOptionPane.showMessageDialog(this, "O nó final não foi encontrado no grafo");
            }
            else
            {
                searchParameter.setEndCityNode(endNode);
            }
            
            if((searchParameter.getStartCityNode() != null) && (searchParameter.getEndCityNode() != null))
            {
                JOptionPane.showMessageDialog(this, "O nó inicial e final foram definidos");
            }
        }
    }//GEN-LAST:event_btnSetStartAndEndNodeActionPerformed

    private void radioAlphabeticalTransitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlphabeticalTransitionActionPerformed
        searchParameter.setTransition(new AlphabeticalTransition());
    }//GEN-LAST:event_radioAlphabeticalTransitionActionPerformed

    private void btnShowGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowGraphActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run() 
            {
                GraphViewerGUI frame = new GraphViewerGUI(searchParameter.getGraph());
		frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnShowGraphActionPerformed

    private void btnSaveGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveGraphActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);
        fileChooser.setCurrentDirectory(new File(FileHelper.WORK_DIR));

        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) 
        {
            try 
            {
                FileHelper.saveGraphFile(fileChooser.getSelectedFile().getName(), searchParameter.getGraph());
                JOptionPane.showMessageDialog(this, "O grafo foi salvo");
            } 
            catch (IOException ex) 
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSaveGraphActionPerformed

    private void btnSaveResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveResultActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);
        fileChooser.setCurrentDirectory(new File(FileHelper.WORK_DIR));

        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) 
        {
            try 
            {
                FileHelper.saveResultFile(fileChooser.getSelectedFile().getName(), algorithmSearch);
                JOptionPane.showMessageDialog(this, "O resultado foi salvo");
            } 
            catch (IOException ex) 
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnSaveResultActionPerformed
    
    private void radioGroupSearchAlgorithmActionPerformed(ActionEvent evt)
    {
        switch(evt.getActionCommand().toUpperCase())
        {
            case "BACKTRACKING":
                searchParameter.setSearchMode(SearchMode.Backtracking);
                break;
            case "BREADTH":
                searchParameter.setSearchMode(SearchMode.Breadth);
                break;
            case "DEPTH":
                searchParameter.setSearchMode(SearchMode.Depth);
                break;
            case "ORDERED":
                searchParameter.setSearchMode(SearchMode.Ordered);
                break;
            case "BESTFIRST":
                searchParameter.setSearchMode(SearchMode.BestFirst);
                break;
            case "A*":
                searchParameter.setSearchMode(SearchMode.A);
                break;
            case "IDA*":
                searchParameter.setSearchMode(SearchMode.IDA);
                break;
        }
        
        this.labelAlgorithmSearchInfo.setText(String.format("Algoritmo de IA: %s", searchParameter.getSearchMode().toString()));
    }
    
    private void clearStatus()
    {
        this.labelStatusSearchInfo.setText("Status: Stopped");
        this.labelSearchExecutionTimeInfo.setText(String.format("Tempo de Execução: %s ms", 0));
        this.labelSearchCostInfo.setText(String.format("Custo da Solução: %s", 0));
        this.labelSearchDepthInfo.setText(String.format("Profundidade da Solução: %s", 0));
        this.labelExpandedNodeCountInfo.setText(String.format("Quantidade de Nós Expandidos: %s", 0));
        this.labelVisitedNodeCountInfo.setText(String.format("Quantidade de Nós Visitados: %s", 0));
        this.labelAverageFactorBranching.setText(String.format("Fator Médio de Ramificação: %s", 0));
        this.txtSearchPathInfo.setText("");
    }
    
    @Override
    public void searchStartedEvent(Object event) 
    {
        this.clearStatus();        
        
        this.btnStartSearch.setEnabled(false);
        this.btnShowSearchTree.setEnabled(false);
        this.btnSaveResult.setEnabled(false);
        
        startSearchTime = System.nanoTime();
    }
    
    @Override
    public void searchStoppedEvent(Object event) 
    {
        endSearchTime = System.nanoTime();
        
        double executionTime = ((endSearchTime - startSearchTime) / 1e6);
        algorithmSearch.setExecutionTime(executionTime);
        
        this.labelSearchExecutionTimeInfo.setText(String.format("Tempo de Execução: %s ms", algorithmSearch.getExecutionTime()));
        this.labelSearchCostInfo.setText(String.format("Custo da Solução: %s", algorithmSearch.getSolutionCost()));
        this.labelSearchDepthInfo.setText(String.format("Profundidade da Solução: %s", algorithmSearch.getSolutionDepth()));
        this.labelExpandedNodeCountInfo.setText(String.format("Quantidade de Nós Expandidos: %s", algorithmSearch.getSolutionExpandedNodeCount()));
        this.labelVisitedNodeCountInfo.setText(String.format("Quantidade de Nós Visitados: %s", algorithmSearch.getSolutionVisitedNodeCount()));
        this.labelAverageFactorBranching.setText(String.format("Fator Médio de Ramificação: %s", algorithmSearch.getSolutionAverageFactorBranching()));
        this.txtSearchPathInfo.setText(algorithmSearch.getSolutionPath());
        
        this.btnStartSearch.setEnabled(true);
        this.btnShowSearchTree.setEnabled(true);
        this.btnSaveResult.setEnabled(true);
    }
    
    @Override
    public void searchStatusChangedEvent(Object event) 
    {
        this.labelStatusSearchInfo.setText(String.format("Status: %s", algorithmSearch.getSearchState().toString()));
    }
    
    private static CityGraph randomGraph(int maxCities, int maxAdjacency)
    {
        CityGraph graph = new CityGraph();
        
        for(int i = 0; i < maxCities; i++)
        {
            graph.addNode(-1, new City(String.valueOf(i), new GeoCoordinate(-1, -1)));
        }
        
        float costAdj;
        int rndIndex1;
        int rndIndex2;
        Random rand = new Random();
        
        for(int i = 0; i < maxCities; i++)
        {
            for(int j = 0; j < maxAdjacency; j++)
            {
                costAdj = rand.nextInt(500);
                rndIndex1 = rand.nextInt(maxCities);
                rndIndex2 = rand.nextInt(maxCities);
            
                graph.addAdjacency(graph.getNode(rndIndex1), graph.getNode(rndIndex2), costAdj, false);
            }
        }
        
        return graph;
    }
    
    private CityGraph createGraph()
    {
        City cityA = new City("A", new GeoCoordinate(-1, -1));
        City cityB = new City("B", new GeoCoordinate(-1, -1));
        City cityC = new City("C", new GeoCoordinate(-1, -1));
        City cityD = new City("D", new GeoCoordinate(-1, -1));
        City cityE = new City("E", new GeoCoordinate(-1, -1));
        City cityF = new City("F", new GeoCoordinate(-1, -1));

        CityGraph graph = new CityGraph();
        graph.addNode(0, cityA);
        graph.addNode(0, cityB);
        graph.addNode(0, cityC);
        graph.addNode(0, cityD);
        graph.addNode(0, cityE);
        graph.addNode(0, cityF);

        graph.addAdjacency(graph.getNode(cityA), graph.getNode(cityB), 20, false);
        graph.addAdjacency(graph.getNode(cityA), graph.getNode(cityC), 10, false);
        graph.addAdjacency(graph.getNode(cityA), graph.getNode(cityD), 5, false);

        graph.addAdjacency(graph.getNode(cityB), graph.getNode(cityC), 25, false);
        graph.addAdjacency(graph.getNode(cityB), graph.getNode(cityD), 15, false);

        graph.addAdjacency(graph.getNode(cityC), graph.getNode(cityD), 30, false);
        graph.addAdjacency(graph.getNode(cityC), graph.getNode(cityE), 15, false);

        graph.addAdjacency(graph.getNode(cityD), graph.getNode(cityE), 10, false);

        graph.addAdjacency(graph.getNode(cityE), graph.getNode(cityF), 5, false);
        
        return graph;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IACityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IACityGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateGraph;
    private javax.swing.JButton btnSaveGraph;
    private javax.swing.JButton btnSaveResult;
    private javax.swing.JButton btnSetStartAndEndNode;
    private javax.swing.JButton btnShowGraph;
    private javax.swing.JButton btnShowSearchTree;
    private javax.swing.JButton btnStartSearch;
    private javax.swing.JCheckBox checkBoxEnableDuplicated;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelAlgorithmSearchInfo;
    private javax.swing.JLabel labelAverageFactorBranching;
    private javax.swing.JLabel labelExpandedNodeCountInfo;
    private javax.swing.JLabel labelSearchCostInfo;
    private javax.swing.JLabel labelSearchDepthInfo;
    private javax.swing.JLabel labelSearchExecutionTimeInfo;
    private javax.swing.JLabel labelStatusSearchInfo;
    private javax.swing.JLabel labelVisitedNodeCountInfo;
    private javax.swing.JRadioButton radioASearch;
    private javax.swing.JRadioButton radioAlphabeticalTransition;
    private javax.swing.JRadioButton radioBTSearch;
    private javax.swing.JRadioButton radioBestFirstSearch;
    private javax.swing.JRadioButton radioBreadthSearch;
    private javax.swing.JRadioButton radioDepthSearch;
    private javax.swing.ButtonGroup radioGroupCreateGraph;
    private javax.swing.ButtonGroup radioGroupSearchAlgorithm;
    private javax.swing.ButtonGroup radioGroupSearchTransition;
    private javax.swing.JRadioButton radioIDASearch;
    private javax.swing.JRadioButton radioManualGraph;
    private javax.swing.JRadioButton radioMapsGraph;
    private javax.swing.JRadioButton radioOrderedSearch;
    private javax.swing.JRadioButton radioTxtFileGraph;
    private javax.swing.JTextField txtEndNodeID;
    private javax.swing.JTextArea txtSearchPathInfo;
    private javax.swing.JTextField txtStartNodeID;
    // End of variables declaration//GEN-END:variables

}
